### ISSUE TITLE
line 17  

### ISSUE THREAD

**Issue by tom-ha** [chn555/nama#1]
tom@debian 14:42:51:~/git/NAM$ bash -x functions.sh 
+ Filter_Active_Interfaces
+ echo Looking for active interfaces...
Looking for active interfaces...
+ echo ''

+ sleep 1
+ readarray -t Active_Interfaces
++ nmcli -t con show --active
**Error: Option '--terse' requires specifying '--fields'.**
+ Menu_Active_Interfaces 0
+ [[ 0 -eq 0 ]]
+ echo No interface is found, exiting.
No interface is found, exiting.
+ sleep 1
+ exit 0

**Comment by chn555** [comment]
Which version of nmcli and bash are you using

**Comment by chn555** [comment]
check now, should be fixed
